<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.3.1 setup script
 * Date: Wed, 06 Jan 2016 03:43:55 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'raspberry';
$cfg['Servers'][$i]['nopassword'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = '568c6e71489ce2.10992464';
$cfg['DefaultLang'] = 'en';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ServerDefault'] = 1;
?>